In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
flight = pd.read_csv(r'itineraries.csv',nrows=5000000)
flight

,legId,searchDate,flightDate,startingAirport,destinationAirport,fareBasisCode,travelDuration,elapsedDays,isBasicEconomy,isRefundable,...,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
0,9ca0e81111c683bec1012473feefd28f,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H29M,0,False,False,...,1650223560,2022-04-17T15:26:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,8940,947,coach
1,98685953630e772a098941b71906592b,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H30M,0,False,False,...,1650200400,2022-04-17T09:00:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9000,947,coach
2,98d90cbc32bfbb05c2fc32897c7c1087,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H30M,0,False,False,...,1650218700,2022-04-17T14:05:00.000-04:00,BOS,ATL,Delta,DL,Boeing 757-200,9000,947,coach
3,969a269d38eae583f455486fa90877b4,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H32M,0,False,False,...,1650227460,2022-04-17T16:31:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9120,947,coach
4,980370cf27c89b40d2833a1d5afc9751,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H34M,0,False,False,...,1650213180,2022-04-17T12:33:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9240,947,coach
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4999995,c7f6bfaf38d3116b1d0bc2db5a23b435,2022-04-27,2022-06-16,LAX,DFW,QAA0OKEN,PT5H46M,0,False,False,...,1655429640||1655441760,2022-06-16T19:34:00.000-06:00||2022-06-16T23:5...,DEN||DFW,LAX||DEN,United||United,UA||UA,Boeing 737-900||Airbus A319,8640||6960,848||650,coach||coach
4999996,6e80834f62e373808231583b74dd95c9,2022-04-27,2022-06-16,LAX,DFW,QAA0OKEN,PT7H13M,0,False,False,...,1655411940||1655429100,2022-06-16T14:39:00.000-06:00||2022-06-16T20:2...,DEN||DFW,LAX||DEN,United||United,UA||UA,Boeing 737 MAX 9||Airbus A320,8820||7200,848||650,coach||coach
4999997,8c8fd3a8c548f59c90086248a73c8856,2022-04-27,2022-06-16,LAX,DFW,UAA0OQEN,PT5H50M,0,False,False,...,1655377680||1655386800,2022-06-16T06:08:00.000-05:00||2022-06-16T08:4...,IAH||DFW,LAX||IAH,United||United,UA||UA,Boeing 737-900||Airbus A320,11880||4200,1383||233,coach||coach
4999998,42a1d959893ba5ba25bffe73535f50dd,2022-04-27,2022-06-16,LAX,DFW,UAA0OQEN,PT5H43M,0,False,False,...,1655416920||1655425140,2022-06-16T17:02:00.000-05:00||2022-06-16T19:1...,IAH||DFW,LAX||IAH,United||United,UA||UA,Boeing 737-800||Airbus A319,12360||4440,1383||233,coach||coach
4999999,33a30fd96281191ce212e97478c24e93,2022-04-27,2022-06-16,LAX,DFW,HAA0OKEN,PT5H22M,0,False,False,...,1655418660||1655429100,2022-06-16T16:31:00.000-06:00||2022-06-16T20:2...,DEN||DFW,ONT||DEN,United||United,UA||UA,Canadian Regional Jet 700||Airbus A320,8880||7200,827||650,coach||coach

In [3]:
flight.head()

,legId,searchDate,flightDate,startingAirport,destinationAirport,fareBasisCode,travelDuration,elapsedDays,isBasicEconomy,isRefundable,...,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
0,9ca0e81111c683bec1012473feefd28f,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H29M,0,False,False,...,1650223560,2022-04-17T15:26:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,8940,947,coach
1,98685953630e772a098941b71906592b,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H30M,0,False,False,...,1650200400,2022-04-17T09:00:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9000,947,coach
2,98d90cbc32bfbb05c2fc32897c7c1087,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H30M,0,False,False,...,1650218700,2022-04-17T14:05:00.000-04:00,BOS,ATL,Delta,DL,Boeing 757-200,9000,947,coach
3,969a269d38eae583f455486fa90877b4,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H32M,0,False,False,...,1650227460,2022-04-17T16:31:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9120,947,coach
4,980370cf27c89b40d2833a1d5afc9751,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H34M,0,False,False,...,1650213180,2022-04-17T12:33:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9240,947,coach

In [4]:
flight.head(10)

,legId,searchDate,flightDate,startingAirport,destinationAirport,fareBasisCode,travelDuration,elapsedDays,isBasicEconomy,isRefundable,...,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
0,9ca0e81111c683bec1012473feefd28f,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H29M,0,False,False,...,1650223560,2022-04-17T15:26:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,8940,947,coach
1,98685953630e772a098941b71906592b,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H30M,0,False,False,...,1650200400,2022-04-17T09:00:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9000,947,coach
2,98d90cbc32bfbb05c2fc32897c7c1087,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H30M,0,False,False,...,1650218700,2022-04-17T14:05:00.000-04:00,BOS,ATL,Delta,DL,Boeing 757-200,9000,947,coach
3,969a269d38eae583f455486fa90877b4,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H32M,0,False,False,...,1650227460,2022-04-17T16:31:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9120,947,coach
4,980370cf27c89b40d2833a1d5afc9751,2022-04-16,2022-04-17,ATL,BOS,LA0NX0MC,PT2H34M,0,False,False,...,1650213180,2022-04-17T12:33:00.000-04:00,BOS,ATL,Delta,DL,Airbus A321,9240,947,coach
5,79eda9f841e226a1e2121d74211e595c,2022-04-16,2022-04-17,ATL,BOS,VH0AUEL1,PT2H38M,0,False,False,...,1650216180,2022-04-17T13:23:00.000-04:00,BOS,ATL,JetBlue Airways,B6,NaN,9480,947,coach
6,9335fae376c38bb61263281779f469ec,2022-04-16,2022-04-17,ATL,BOS,V0AJZNN1,PT4H12M,0,False,False,...,1650203400||1650213120,2022-04-17T09:50:00.000-04:00||2022-04-17T12:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A320||Airbus A320,5400||7500,228||728,coach||coach
7,3904bf87f2d1daf334f1ae7e3b876028,2022-04-16,2022-04-17,ATL,BOS,V0AJZNN1,PT5H18M,0,False,False,...,1650203400||1650217080,2022-04-17T09:50:00.000-04:00||2022-04-17T13:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A320||Boeing 737-800,5400||8280,228||728,coach||coach
8,d93988734c44a3c075d9efe373352507,2022-04-16,2022-04-17,ATL,BOS,V0AJZNN1,PT5H32M,0,False,False,...,1650198060||1650213120,2022-04-17T08:21:00.000-04:00||2022-04-17T12:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A319||Airbus A320,4860||7500,228||728,coach||coach
9,562e7d5dd6ecbf1509c0c19711dbdca9,2022-04-16,2022-04-17,ATL,BOS,V0AJZNN1,PT6H38M,0,False,False,...,1650198060||1650217080,2022-04-17T08:21:00.000-04:00||2022-04-17T13:3...,CLT||BOS,ATL||CLT,American Airlines||American Airlines,AA||AA,Airbus A319||Boeing 737-800,4860||8280,228||728,coach||coach

In [5]:
flight.tail()

,legId,searchDate,flightDate,startingAirport,destinationAirport,fareBasisCode,travelDuration,elapsedDays,isBasicEconomy,isRefundable,...,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
4999995,c7f6bfaf38d3116b1d0bc2db5a23b435,2022-04-27,2022-06-16,LAX,DFW,QAA0OKEN,PT5H46M,0,False,False,...,1655429640||1655441760,2022-06-16T19:34:00.000-06:00||2022-06-16T23:5...,DEN||DFW,LAX||DEN,United||United,UA||UA,Boeing 737-900||Airbus A319,8640||6960,848||650,coach||coach
4999996,6e80834f62e373808231583b74dd95c9,2022-04-27,2022-06-16,LAX,DFW,QAA0OKEN,PT7H13M,0,False,False,...,1655411940||1655429100,2022-06-16T14:39:00.000-06:00||2022-06-16T20:2...,DEN||DFW,LAX||DEN,United||United,UA||UA,Boeing 737 MAX 9||Airbus A320,8820||7200,848||650,coach||coach
4999997,8c8fd3a8c548f59c90086248a73c8856,2022-04-27,2022-06-16,LAX,DFW,UAA0OQEN,PT5H50M,0,False,False,...,1655377680||1655386800,2022-06-16T06:08:00.000-05:00||2022-06-16T08:4...,IAH||DFW,LAX||IAH,United||United,UA||UA,Boeing 737-900||Airbus A320,11880||4200,1383||233,coach||coach
4999998,42a1d959893ba5ba25bffe73535f50dd,2022-04-27,2022-06-16,LAX,DFW,UAA0OQEN,PT5H43M,0,False,False,...,1655416920||1655425140,2022-06-16T17:02:00.000-05:00||2022-06-16T19:1...,IAH||DFW,LAX||IAH,United||United,UA||UA,Boeing 737-800||Airbus A319,12360||4440,1383||233,coach||coach
4999999,33a30fd96281191ce212e97478c24e93,2022-04-27,2022-06-16,LAX,DFW,HAA0OKEN,PT5H22M,0,False,False,...,1655418660||1655429100,2022-06-16T16:31:00.000-06:00||2022-06-16T20:2...,DEN||DFW,ONT||DEN,United||United,UA||UA,Canadian Regional Jet 700||Airbus A320,8880||7200,827||650,coach||coach

In [6]:
flight.sample(5)

,legId,searchDate,flightDate,startingAirport,destinationAirport,fareBasisCode,travelDuration,elapsedDays,isBasicEconomy,isRefundable,...,segmentsArrivalTimeEpochSeconds,segmentsArrivalTimeRaw,segmentsArrivalAirportCode,segmentsDepartureAirportCode,segmentsAirlineName,segmentsAirlineCode,segmentsEquipmentDescription,segmentsDurationInSeconds,segmentsDistance,segmentsCabinCode
537350,96aa0b316b0ec498d9b77cbaeb051369,2022-04-17,2022-06-07,IAD,JFK,G7AHZNN1,PT8H39M,0,False,False,...,1654598340||1654611720||1654624740,2022-06-07T06:39:00.000-04:00||2022-06-07T10:2...,CLT||RDU||JFK,IAD||CLT||RDU,American Airlines||American Airlines||American...,AA||AA||AA,Boeing 737-800||Airbus A320||Embraer 175,4740||3720||6480,327||130||434,coach||coach||coach
1194284,d599e84f4ca47e66c2e614db742e8c5c,2022-04-19,2022-05-02,LGA,SFO,OL7AUEL1,PT9H34M,0,False,False,...,1651490880||1651521240,2022-05-02T07:28:00.000-04:00||2022-05-02T12:5...,BOS||SFO,LGA||BOS,JetBlue Airways||JetBlue Airways,B6||B6,Embraer 190||Airbus A319-321,4080||24300,185||2698,coach||coach
4472103,abff7048d32ec9f47eafe5f16d0ae7bb,2022-04-26,2022-05-20,DEN,OAK,TAVNA0BC,PT4H31M,0,True,False,...,1653051960||1653062460,2022-05-20T07:06:00.000-06:00||2022-05-20T09:0...,SLC||OAK,DEN||SLC,Delta||Delta,DL||DL,Boeing 737-800||,5760||6960,380||588,coach||coach
2476669,cfe277a998eb689b031368700d4d71c4,2022-04-22,2022-04-25,BOS,LAX,VAA3KKEN,PT8H58M,0,False,False,...,1650915060||1650941880,2022-04-25T15:31:00.000-04:00||2022-04-25T19:5...,EWR||LAX,BOS||EWR,United||United,UA||UA,Airbus A319||,5460||21480,185||2458,coach||coach
984414,e516445fdcebbf4f0a24ad90c286a48c,2022-04-18,2022-05-28,SFO,EWR,MAUNA0MC,PT6H49M,1,False,False,...,1653789780||1653798240,2022-05-28T22:03:00.000-04:00||2022-05-29T00:2...,DTW||EWR,SFO||DTW,Delta||Delta,DL||DL,Boeing 737-900||Boeing 717,16080||5640,2083||485,coach||coach

In [7]:
flight.shape

(5000000, 27)

In [8]:
flight.size

135000000

In [9]:
flight.dtypes

legId                                 object
searchDate                            object
flightDate                            object
startingAirport                       object
destinationAirport                    object
fareBasisCode                         object
travelDuration                        object
elapsedDays                            int64
isBasicEconomy                          bool
isRefundable                            bool
isNonStop                               bool
baseFare                             float64
totalFare                            float64
seatsRemaining                         int64
totalTravelDistance                  float64
segmentsDepartureTimeEpochSeconds     object
segmentsDepartureTimeRaw              object
segmentsArrivalTimeEpochSeconds       object
segmentsArrivalTimeRaw                object
segmentsArrivalAirportCode            object
segmentsDepartureAirportCode          object
segmentsAirlineName                   object
segmentsAirlineCode                   object
segmentsEquipmentDescription          object
segmentsDurationInSeconds             object
segmentsDistance                      object
segmentsCabinCode                     object
dtype: object

In [10]:
flight.index

RangeIndex(start=0, stop=5000000, step=1)

In [11]:
flight.columns

Index(['legId', 'searchDate', 'flightDate', 'startingAirport',
       'destinationAirport', 'fareBasisCode', 'travelDuration', 'elapsedDays',
       'isBasicEconomy', 'isRefundable', 'isNonStop', 'baseFare', 'totalFare',
       'seatsRemaining', 'totalTravelDistance',
       'segmentsDepartureTimeEpochSeconds', 'segmentsDepartureTimeRaw',
       'segmentsArrivalTimeEpochSeconds', 'segmentsArrivalTimeRaw',
       'segmentsArrivalAirportCode', 'segmentsDepartureAirportCode',
       'segmentsAirlineName', 'segmentsAirlineCode',
       'segmentsEquipmentDescription', 'segmentsDurationInSeconds',
       'segmentsDistance', 'segmentsCabinCode'],
      dtype='object')

In [12]:
flight.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000000 entries, 0 to 4999999
Data columns (total 27 columns):
 #   Column                             Dtype
---  ------                             -----
 0   legId                              object
 1   searchDate                         object
 2   flightDate                         object
 3   startingAirport                    object
 4   destinationAirport                 object
 5   fareBasisCode                      object
 6   travelDuration                     object
 7   elapsedDays                        int64
 8   isBasicEconomy                     bool
 9   isRefundable                       bool
 10  isNonStop                          bool
 11  baseFare                           float64
 12  totalFare                          float64
 13  seatsRemaining                     int64
 14  totalTravelDistance                float64
 15  segmentsDepartureTimeEpochSeconds  object
 16  segmentsDepartureTimeRaw           object
 17  segmentsArrivalTimeEpochSeconds    object
 18  segmentsArrivalTimeRaw             object
 19  segmentsArrivalAirportCode         object
 20  segmentsDepartureAirportCode       object
 21  segmentsAirlineName                object
 22  segmentsAirlineCode                object
 23  segmentsEquipmentDescription       object
 24  segmentsDurationInSeconds          object
 25  segmentsDistance                   object
 26  segmentsCabinCode                  object
dtypes: bool(3), float64(3), int64(2), object(19)
memory usage: 929.8+ MB

In [13]:
flight.describe()

,elapsedDays,baseFare,totalFare,seatsRemaining,totalTravelDistance
count,5.000000e+06,5.000000e+06,5.000000e+06,5.000000e+06,4.682132e+06
mean,1.469112e-01,3.032033e+02,3.516310e+02,5.659033e+00,1.572933e+03
std,3.540231e-01,1.950507e+02,2.093218e+02,2.935401e+00,8.391262e+02
min,0.000000e+00,5.100000e+00,2.397000e+01,0.000000e+00,9.700000e+01
25%,0.000000e+00,1.674400e+02,2.056000e+02,3.000000e+00,8.620000e+02
50%,0.000000e+00,2.734900e+02,3.206000e+02,7.000000e+00,1.392000e+03
75%,0.000000e+00,4.037200e+02,4.576000e+02,8.000000e+00,2.353000e+03
max,2.000000e+00,7.662330e+03,8.260610e+03,1.000000e+01,3.958000e+03

In [14]:
type(flight)

pandas.core.frame.DataFrame

In [15]:
flight.flightDate.unique()

array(['2022-04-17', '2022-04-18', '2022-04-19', '2022-04-20',
       '2022-04-21', '2022-04-22', '2022-04-23', '2022-04-24',
       '2022-04-25', '2022-04-26', '2022-04-27', '2022-04-28',
       '2022-04-29', '2022-04-30', '2022-05-01', '2022-05-02',
       '2022-05-03', '2022-05-04', '2022-05-05', '2022-05-06',
       '2022-05-07', '2022-05-08', '2022-05-09', '2022-05-10',
       '2022-05-11', '2022-05-12', '2022-05-13', '2022-05-14',
       '2022-05-15', '2022-05-16', '2022-05-17', '2022-05-18',
       '2022-05-19', '2022-05-20', '2022-05-21', '2022-05-22',
       '2022-05-23', '2022-05-24', '2022-05-25', '2022-05-26',
       '2022-05-27', '2022-05-28', '2022-05-29', '2022-05-30',
       '2022-05-31', '2022-06-01', '2022-06-02', '2022-06-03',
       '2022-06-04', '2022-06-05', '2022-06-06', '2022-06-07',
       '2022-06-08', '2022-06-09', '2022-06-10', '2022-06-11',
       '2022-06-12', '2022-06-13', '2022-06-14', '2022-06-15',
       '2022-06-16', '2022-06-17', '2022-06-18', '2022-06-19',
       '2022-06-20', '2022-06-21', '2022-06-22', '2022-06-23',
       '2022-06-24'], dtype=object)

In [16]:
flight.flightDate.nunique()

69

In [17]:
flight.flightDate.value_counts()

flightDate
2022-05-03    120002
2022-05-10    113966
2022-05-04    110983
2022-04-26    107712
2022-05-11    107631
               ...
2022-06-22     17537
2022-04-18     16524
2022-06-23      9041
2022-04-17      8258
2022-06-24      1951
Name: count, Length: 69, dtype: int64

In [18]:
flight["flightDate"] = pd.to_datetime(flight["flightDate"])
may_flights = flight[flight["flightDate"].dt.month == 5]
may_flights.to_csv("itineraries_clear.csv", index=False)

print("Number of flights in May:", len(may_flights))

Number of flights in May: 2873519